# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    ë¼ë²¨ ì§€ì • ì œëŒ€ë¡œ ë˜ì—ˆëŠ”ì§€ ì²´í¬ í•œ ë²ˆì”© í•˜ê¸° ğŸ§â€â™‚ï¸ ì‘ì—…ë„ í™”ì´íŒ… !!!!!!! ğŸ˜
  prs: |
    ë¼ë²¨ ì§€ì • ì œëŒ€ë¡œ ë˜ì—ˆëŠ”ì§€ ì²´í¬ í•œ ë²ˆì”© í•˜ê¸° ğŸ§â€â™‚ï¸ ê³ ìƒí–ˆì–´ìš” ë‹¤ìŒ ì‘ì—…ë„ í™”ì´íŒ… !!!!!! ğŸ˜
    

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  ':tada: init':
    include:
      - '\binit\b'
  ':sparkles: feat':
    include:
      - '\bfeat\b'
  ':bug: fix':
    include:
      - '\bfix\b'
  ':package: chore':
    include:
      - '\bchore\b'
  ':recycle: refactor':
    include:
      - '\brefactor\b'
  ':lipstick: design':
    include:
      - '\bdesign\b'
  ':ambulance: hotfix':
    include:
      - '\bhotfix\b'
  ':memo: docs':
    include:
      - '\bdocs\b'
